### ISSUE TITLE
Single page routing tut's nicht so recht

### ISSUE THREAD

**Issue by webwurst** [codeformuenster/muenster-dashboard#17]
Wenn ich direkt `https://mein-ms.de/stadtviertel` aufrufe, also im "private mode" oder mit `ctrl+shift+r`, dann bekomme ich `404 Not found`

@tomsrocket hast du ne idee dazu?

**Update:** Vermutlich hilft die neue regex-ingress option dabei..

**Comment by ubergesundheit** [comment]
Da fehlen redirects, weil das Ding ne Single-page application ist , das routing macht react in diesem Fall.
Also würde es wohl reichen, in diesem Fall `/stadtviertel` auf `/` redirecten zu lassen

**Comment by tomsrocket** [comment]
Habe gerade leider keine Zeit mir das anzuschauen.. Da muss wahrscheinlich eine rewrite rule rein wie Gerald sagt
