### ISSUE TITLE
Alternativen elasticsearch server einbauen

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/muenster-dashboard#74]
Der Alternative elasticsearch läuft jetzt unter data.mein-ms.de

Wir brauchen  eine Abfrage im Code, die erstmal checkt ob der primäre elasticsearch cluster läuft, und ansonsten auf data.mein-ms.de umspringt.

**Comment by tomsrocket** [comment]
1. Funktioniert noch nicht, möglicherweise wegen fehlendem SSL Zertifikat (Internet Explorer)

2. Im Edge funktioniert es nicht, da kommt als letzte Meldung der trace aus DistrictService Zeile 47.

3. Firefox besteht bei mir immer noch das Problem dass lat lon null sind und leaflet steigt aus.

4. Auf dem Handy geht's auch nicht.

**Comment by ubergesundheit** [comment]
https://data.mein-ms.de liefert ein Zertifikat aus, dass zwar auf den hostnamen passt, aber am 13. April abgelaufen ist. Glaube das sollte erstmal das größte Problem sein.

**Comment by tomsrocket** [comment]
Elasticsearch tut's nicht so gut auf dem Cluster daher nehmen wir statt dessen die Elasticsearch-Installation auf dem VServer. Ist eingebaut und läuft erstmal gut, ich schließe das Ticket.
