### ISSUE TITLE
"security vulnerability" beheben

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/muenster-dashboard#76]
Github meckert. Man müsste bestimmt nur mal "npm update" machen.

**Comment by ubergesundheit** [comment]
Teilweise hatte ich das schon gemacht in diesem commit e7184d5ab889b6b6f6343f5d22eed2180b85b7b0

Am besten sollte das Projekt per `npm run eject` aus dem `create-react-app-ts` herauslösen, dann können wir die ganzen dependencies updaten

**Comment by u-rogel** [comment]
I just run `npm audit` and there are no warnings, so I guess we can close this issue.
